const {
  NODE_ENV,
  REACT_APP_API_BASE_URL,
  REACT_APP_API_POSTFIX,
  REACT_APP_API_SECRET_KEY_CAREER,
  REACT_APP_API_SECRET_KEY_PROJECT,
  REACT_APP_DATABASE_ID_CAREER,
  REACT_APP_DATABASE_ID_PROJECT,
  REACT_APP_NOTION_VERSION,
} = process.env;

export default {
  NODE_ENV,
  API_BASE_URL: REACT_APP_API_BASE_URL,
  API_POSTFIX: REACT_APP_API_POSTFIX,
  SECRET_KEY_CAREER: REACT_APP_API_SECRET_KEY_CAREER,
  SECRET_KEY_PROJECT: REACT_APP_API_SECRET_KEY_PROJECT,
  DATABASE_ID_CAREER: REACT_APP_DATABASE_ID_CAREER,
  DATABASE_ID_PROJECT: REACT_APP_DATABASE_ID_PROJECT,
  NOTION_VERSION: REACT_APP_NOTION_VERSION,
};
